# Generated by Django 5.2.12 on 2026-08-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="creado el"
            ),
        ),
    ]
