# Generated by Django 5.2.12 on 2026-03-12 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=50, verbose_name="módulo")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Creación"),
                            ("update", "Actualización"),
                            ("delete", "Eliminación"),
                            ("send", "Envío"),
                            ("receive", "Recepción"),
                            ("cancel", "Cancelación"),
                            ("import", "Importación"),
                        ],
                        max_length=20,
                        verbose_name="acción",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(max_length=100, verbose_name="tipo de objeto"),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ID de objeto"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="representación"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado el"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoría",
                "verbose_name_plural": "registros de auditoría",
                "ordering": ["-created_at"],
            },
        ),
    ]
