# Generated by Django 5.2.12 on 2026-03-12 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0002_purchaseorder_purchaseorderitem_productsupplier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("send_purchaseorder", "Can send purchase order"),
                    ("receive_purchaseorder", "Can receive purchase order"),
                    ("cancel_purchaseorder", "Can cancel purchase order"),
                ],
                "verbose_name": "orden de compra",
                "verbose_name_plural": "órdenes de compra",
            },
        ),
    ]
