# Generated by Django 5.2.12 on 2026-08-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0003_alter_purchaseorder_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("sent", "Enviada"),
                    ("received", "Recibida"),
                    ("cancelled", "Cancelada"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="estado",
            ),
        ),
    ]
