# Generated by Django 5.2.12 on 2026-08-17 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock_current",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="stock actual",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_minimum",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="stock mínimo",
            ),
        ),
    ]
