# Generated by Django 5.2.12 on 2026-08-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_product_stock_current_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="activo"
            ),
        ),
    ]
